exp

diff --git a/.github/workflows/size.yml b/.github/workflows/size.yml
--- a/.github/workflows/size.yml
+++ b/.github/workflows/size.yml
@@ -31,28 +31,29 @@ name: Size
 on: [push, pull_request]
 
 jobs:
-
-  cancel-previous-runs:
-    runs-on: ubuntu-latest
-    steps:
-    - uses: rokroskar/workflow-run-cleanup-action@master
-      env:
-        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
-      if: "github.ref != 'refs/heads/master'"
-
-  size-report:
+  success:
     runs-on: ubuntu-18.04
     steps:
-    - uses: actions/checkout@v2
-    - name: Bootstrap
-      if: "github.event_name == 'push'"
-      run: |
-        python3 -m pip install --upgrade setuptools wheel
-        python3 -m pip install mdv
-    - name: Run
-      env:
-        OT_BASE_BRANCH: "${{ github.base_ref }}"
-        SIZE_REPORT_URL: "https://openthread-size-report.glitch.me/size-report/1354027"
-      run: |
-        export PATH=$PATH:$HOME/.local/bin
-        ./script/check-size
+    - run: |
+        echo "Success"
+  failure:
+    runs-on: ubuntu-18.04
+    steps:
+    - run: |
+        echo "Failure"
+        exit 1
+  upload:
+    needs:
+    - success
+    - failure
+    runs-on: ubuntu-18.04
+    steps:
+    - run: |
+        echo "Upload"
+  cleanup:
+    needs: upload
+    if: always()
+    runs-on: ubuntu-18.04
+    steps:
+    - run: |
+        echo "Cleanup"
